#!/usr/bin/env python

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

import logging
from npyscreen import *

log = logging.getLogger(__name__)


BLURB = """This is a simple wizard to configure Errbot.

If you need advanced features like an external backend,
    please use the manual installation procedure.
"""

BACKENDS = ["Slack", "Hipchat", "Telegram", "XMPP", "IRC"]

Form.FIX_MINIMUM_SIZE_WHEN_CREATED = False

class WizardForm(ActionForm):
  OK_BUTTON_TEXT = 'Next'
  def on_ok(self):
    return True
  def on_cancel(self):
    return False

def welcome_screen():
    form  = WizardForm(name = "Welcome to Errbot setup wizard",
                       minimum_lines=24,
                       minimum_columns=80,
                       cycle_widgets=True)
    form.add(MultiLineEdit,
               value = BLURB,
               max_height=5, editable=False)


    backends = form.add(TitleSelectOne,
                        name="Select your target backend",
                        values = BACKENDS,
                        scroll_exit=True, value=[0,])
    return form, backends

def secret_screen(backend):
    form = WizardForm(name = "Enter your credentials for %s" % backend,
                       minimum_lines=24,
                       minimum_columns=80,
                       cycle_widgets=True)
    form.add(TitleText, name = "Token", value = "xoxb-")

    return form

class SetupWizard(NPSApp):
  def main(self):
    welcome, backends = welcome_screen()
    if welcome.edit():
      secret = secret_screen(backends.values[backends.value[0]])
      secret.edit()

if __name__ == "__main__":
    app = SetupWizard()
    app.run()
